target: income
test_size: 0.2
random_state: 42
numeric_features:
  - age
  - fnlwgt
  - hours_per_week
nominal_features:
  - workclass
  - marital_status
  - occupation
  - relationship
  - race
  - gender
  - capital_gain
  - capital_loss
  - native_country
ordinal:
  features:
    - education
  categories:
    education:
      - Preschool
      - 1st-4th
      - 5th-6th
      - 7th-8th
      - 9th
      - 10th
      - 11th
      - 12th
      - HS-grad
      - Some-college
      - Assoc-voc
      - Assoc-acdm
      - Bachelors
      - Masters
      - Prof-school
      - Doctorate
informative_features:
  - occupation
  - capital_gain
  - education
  - relationship
  - gender
  - age
  - marital_status